// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0-alpha.3.0.ci-ZZZ.503841922
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable disable

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Ubiquity.NET.Llvm.Interop
{
    public static partial class NativeMethods
    {
        /// <include file="../../ApiDocs/llvm-c/Comdat.xml" path='LibLlvmAPI/Function[@name="LLVMGetOrInsertComdat"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMComdatRef LLVMGetOrInsertComdat( LLVMModuleRef M, [MarshalAs( UnmanagedType.LPStr )]string Name );

        /// <include file="../../ApiDocs/llvm-c/Comdat.xml" path='LibLlvmAPI/Function[@name="LLVMGetComdat"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMComdatRef LLVMGetComdat( LLVMValueRef V );

        /// <include file="../../ApiDocs/llvm-c/Comdat.xml" path='LibLlvmAPI/Function[@name="LLVMSetComdat"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMSetComdat( LLVMValueRef V, LLVMComdatRef C );

        /// <include file="../../ApiDocs/llvm-c/Comdat.xml" path='LibLlvmAPI/Function[@name="LLVMGetComdatSelectionKind"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMComdatSelectionKind LLVMGetComdatSelectionKind( LLVMComdatRef C );

        /// <include file="../../ApiDocs/llvm-c/Comdat.xml" path='LibLlvmAPI/Function[@name="LLVMSetComdatSelectionKind"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMSetComdatSelectionKind( LLVMComdatRef C, LLVMComdatSelectionKind Kind );

    }
}
