// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0-alpha.3.0.ci-ZZZ.503841922
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable disable

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Ubiquity.NET.Llvm.Interop
{
    public static partial class NativeMethods
    {
        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDebugMetadataVersion"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern uint LLVMDebugMetadataVersion(  );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMGetModuleDebugMetadataVersion"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern uint LLVMGetModuleDebugMetadataVersion( LLVMModuleRef Module );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMStripModuleDebugInfo"]/*' />
        [return: MarshalAs( UnmanagedType.Bool )]
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern bool LLVMStripModuleDebugInfo( LLVMModuleRef Module );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMCreateDIBuilderDisallowUnresolved"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMDIBuilderRef LLVMCreateDIBuilderDisallowUnresolved( LLVMModuleRef M );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMCreateDIBuilder"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMDIBuilderRef LLVMCreateDIBuilder( LLVMModuleRef M );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderFinalize"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMDIBuilderFinalize( LLVMDIBuilderRef Builder );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateCompileUnit"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateCompileUnit( LLVMDIBuilderRef Builder, LLVMDWARFSourceLanguage Lang, LLVMMetadataRef FileRef, [MarshalAs( UnmanagedType.LPStr )]string Producer, size_t ProducerLen, [MarshalAs( UnmanagedType.Bool )]bool isOptimized, [MarshalAs( UnmanagedType.LPStr )]string Flags, size_t FlagsLen, uint RuntimeVer, [MarshalAs( UnmanagedType.LPStr )]string SplitName, size_t SplitNameLen, LLVMDWARFEmissionKind Kind, uint DWOId, [MarshalAs( UnmanagedType.Bool )]bool SplitDebugInlining, [MarshalAs( UnmanagedType.Bool )]bool DebugInfoForProfiling );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateFile"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateFile( LLVMDIBuilderRef Builder, [MarshalAs( UnmanagedType.LPStr )]string Filename, size_t FilenameLen, [MarshalAs( UnmanagedType.LPStr )]string Directory, size_t DirectoryLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateModule"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateModule( LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, [MarshalAs( UnmanagedType.LPStr )]string ConfigMacros, size_t ConfigMacrosLen, [MarshalAs( UnmanagedType.LPStr )]string IncludePath, size_t IncludePathLen, [MarshalAs( UnmanagedType.LPStr )]string SysRoot, size_t SysRootLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateNameSpace"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateNameSpace( LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, [MarshalAs( UnmanagedType.Bool )]bool ExportSymbols );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateFunction"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateFunction( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, [MarshalAs( UnmanagedType.LPStr )]string LinkageName, size_t LinkageNameLen, LLVMMetadataRef File, uint LineNo, LLVMMetadataRef Ty, [MarshalAs( UnmanagedType.Bool )]bool IsLocalToUnit, [MarshalAs( UnmanagedType.Bool )]bool IsDefinition, uint ScopeLine, LLVMDIFlags Flags, [MarshalAs( UnmanagedType.Bool )]bool IsOptimized );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateLexicalBlock"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateLexicalBlock( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, uint Line, uint Column );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateLexicalBlockFile"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateLexicalBlockFile( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, uint Discriminator );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateImportedModuleFromNamespace"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromNamespace( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef NS, LLVMMetadataRef File, uint Line );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateImportedModuleFromAlias"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromAlias( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef ImportedEntity, LLVMMetadataRef File, uint Line );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateImportedModuleFromModule"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromModule( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef M, LLVMMetadataRef File, uint Line );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateImportedDeclaration"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateImportedDeclaration( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef Decl, LLVMMetadataRef File, uint Line, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateDebugLocation"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateDebugLocation( LLVMContextRef Ctx, uint Line, uint Column, LLVMMetadataRef Scope, LLVMMetadataRef InlinedAt );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDILocationGetLine"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern uint LLVMDILocationGetLine( LLVMMetadataRef Location );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDILocationGetColumn"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern uint LLVMDILocationGetColumn( LLVMMetadataRef Location );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDILocationGetScope"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDILocationGetScope( LLVMMetadataRef Location );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDILocationGetInlinedAt"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDILocationGetInlinedAt( LLVMMetadataRef Location );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIScopeGetFile"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIScopeGetFile( LLVMMetadataRef Scope );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIFileGetDirectory"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( AliasStringMarshaler ) )]
        public static extern string LLVMDIFileGetDirectory( LLVMMetadataRef File, out uint Len );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIFileGetFilename"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( AliasStringMarshaler ) )]
        public static extern string LLVMDIFileGetFilename( LLVMMetadataRef File, out uint Len );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIFileGetSource"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( AliasStringMarshaler ) )]
        public static extern string LLVMDIFileGetSource( LLVMMetadataRef File, out uint Len );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderGetOrCreateTypeArray"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderGetOrCreateTypeArray( LLVMDIBuilderRef Builder, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] Data, size_t NumElements );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateSubroutineType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateSubroutineType( LLVMDIBuilderRef Builder, LLVMMetadataRef File, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] ParameterTypes, uint NumParameterTypes, LLVMDIFlags Flags );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateMacro"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateMacro( LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, uint Line, LLVMDWARFMacinfoRecordType RecordType, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, [MarshalAs( UnmanagedType.LPStr )]string Value, size_t ValueLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateTempMacroFile"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateTempMacroFile( LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, uint Line, LLVMMetadataRef File );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateEnumerator"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateEnumerator( LLVMDIBuilderRef Builder, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, global::System.Int64 Value, [MarshalAs( UnmanagedType.Bool )]bool IsUnsigned );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateEnumerationType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateEnumerationType( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNumber, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] Elements, uint NumElements, LLVMMetadataRef ClassTy );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateUnionType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateUnionType( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNumber, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, LLVMDIFlags Flags, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] Elements, uint NumElements, uint RunTimeLang, [MarshalAs( UnmanagedType.LPStr )]string UniqueId, size_t UniqueIdLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateArrayType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateArrayType( LLVMDIBuilderRef Builder, global::System.UInt64 Size, global::System.UInt32 AlignInBits, LLVMMetadataRef Ty, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] Subscripts, uint NumSubscripts );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateVectorType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateVectorType( LLVMDIBuilderRef Builder, global::System.UInt64 Size, global::System.UInt32 AlignInBits, LLVMMetadataRef Ty, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] Subscripts, uint NumSubscripts );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateUnspecifiedType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateUnspecifiedType( LLVMDIBuilderRef Builder, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateBasicType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateBasicType( LLVMDIBuilderRef Builder, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, global::System.UInt64 SizeInBits, global::System.UInt32 Encoding, LLVMDIFlags Flags );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreatePointerType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreatePointerType( LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeTy, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, uint AddressSpace, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateStructType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateStructType( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNumber, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] Elements, uint NumElements, uint RunTimeLang, LLVMMetadataRef VTableHolder, [MarshalAs( UnmanagedType.LPStr )]string UniqueId, size_t UniqueIdLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateMemberType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateMemberType( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNo, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, global::System.UInt64 OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateStaticMemberType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateStaticMemberType( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNumber, LLVMMetadataRef Type, LLVMDIFlags Flags, LLVMValueRef ConstantVal, global::System.UInt32 AlignInBits );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateMemberPointerType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateMemberPointerType( LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeType, LLVMMetadataRef ClassType, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, LLVMDIFlags Flags );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateObjCIVar"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateObjCIVar( LLVMDIBuilderRef Builder, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNo, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, global::System.UInt64 OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty, LLVMMetadataRef PropertyNode );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateObjCProperty"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateObjCProperty( LLVMDIBuilderRef Builder, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNo, [MarshalAs( UnmanagedType.LPStr )]string GetterName, size_t GetterNameLen, [MarshalAs( UnmanagedType.LPStr )]string SetterName, size_t SetterNameLen, uint PropertyAttributes, LLVMMetadataRef Ty );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateObjectPointerType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateObjectPointerType( LLVMDIBuilderRef Builder, LLVMMetadataRef Type );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateQualifiedType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateQualifiedType( LLVMDIBuilderRef Builder, uint Tag, LLVMMetadataRef Type );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateReferenceType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateReferenceType( LLVMDIBuilderRef Builder, uint Tag, LLVMMetadataRef Type );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateNullPtrType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateNullPtrType( LLVMDIBuilderRef Builder );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateTypedef"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateTypedef( LLVMDIBuilderRef Builder, LLVMMetadataRef Type, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNo, LLVMMetadataRef Scope, global::System.UInt32 AlignInBits );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateInheritance"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateInheritance( LLVMDIBuilderRef Builder, LLVMMetadataRef Ty, LLVMMetadataRef BaseTy, global::System.UInt64 BaseOffset, global::System.UInt32 VBPtrOffset, LLVMDIFlags Flags );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateForwardDecl"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateForwardDecl( LLVMDIBuilderRef Builder, uint Tag, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, uint Line, uint RuntimeLang, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, [MarshalAs( UnmanagedType.LPStr )]string UniqueIdentifier, size_t UniqueIdentifierLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateReplaceableCompositeType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateReplaceableCompositeType( LLVMDIBuilderRef Builder, uint Tag, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, uint Line, uint RuntimeLang, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, LLVMDIFlags Flags, [MarshalAs( UnmanagedType.LPStr )]string UniqueIdentifier, size_t UniqueIdentifierLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateBitFieldMemberType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateBitFieldMemberType( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNumber, global::System.UInt64 SizeInBits, global::System.UInt64 OffsetInBits, global::System.UInt64 StorageOffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Type );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateClassType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateClassType( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNumber, global::System.UInt64 SizeInBits, global::System.UInt32 AlignInBits, global::System.UInt64 OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, out LLVMMetadataRef Elements, uint NumElements, LLVMMetadataRef VTableHolder, LLVMMetadataRef TemplateParamsNode, [MarshalAs( UnmanagedType.LPStr )]string UniqueIdentifier, size_t UniqueIdentifierLen );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateArtificialType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateArtificialType( LLVMDIBuilderRef Builder, LLVMMetadataRef Type );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDITypeGetName"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( AliasStringMarshaler ) )]
        public static extern string LLVMDITypeGetName( LLVMMetadataRef DType, out size_t Length );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDITypeGetSizeInBits"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::System.UInt64 LLVMDITypeGetSizeInBits( LLVMMetadataRef DType );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDITypeGetOffsetInBits"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::System.UInt64 LLVMDITypeGetOffsetInBits( LLVMMetadataRef DType );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDITypeGetAlignInBits"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::System.UInt32 LLVMDITypeGetAlignInBits( LLVMMetadataRef DType );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDITypeGetLine"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern uint LLVMDITypeGetLine( LLVMMetadataRef DType );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDITypeGetFlags"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMDIFlags LLVMDITypeGetFlags( LLVMMetadataRef DType );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderGetOrCreateSubrange"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderGetOrCreateSubrange( LLVMDIBuilderRef Builder, global::System.Int64 LowerBound, global::System.Int64 Count );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderGetOrCreateArray"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderGetOrCreateArray( LLVMDIBuilderRef Builder, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.SysInt )]LLVMMetadataRef[] Data, size_t NumElements );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateExpression"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateExpression( LLVMDIBuilderRef Builder, [In][MarshalAs( UnmanagedType.LPArray, ArraySubType = UnmanagedType.I8 )]global::System.Int64[] Addr, size_t Length );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateConstantValueExpression"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateConstantValueExpression( LLVMDIBuilderRef Builder, global::System.Int64 Value );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateGlobalVariableExpression"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateGlobalVariableExpression( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, [MarshalAs( UnmanagedType.LPStr )]string Linkage, size_t LinkLen, LLVMMetadataRef File, uint LineNo, LLVMMetadataRef Ty, [MarshalAs( UnmanagedType.Bool )]bool LocalToUnit, LLVMMetadataRef Expr, LLVMMetadataRef Decl, global::System.UInt32 AlignInBits );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIGlobalVariableExpressionGetVariable"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIGlobalVariableExpressionGetVariable( LLVMMetadataRef GVE );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIGlobalVariableExpressionGetExpression"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIGlobalVariableExpressionGetExpression( LLVMMetadataRef GVE );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIVariableGetFile"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIVariableGetFile( LLVMMetadataRef Var );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIVariableGetScope"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIVariableGetScope( LLVMMetadataRef Var );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIVariableGetLine"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern uint LLVMDIVariableGetLine( LLVMMetadataRef Var );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMTemporaryMDNode"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMTemporaryMDNode( LLVMContextRef Ctx, out LLVMMetadataRef Data, size_t NumElements );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDisposeTemporaryMDNode"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMDisposeTemporaryMDNode( LLVMMetadataRef TempNode );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMMetadataReplaceAllUsesWith"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMMetadataReplaceAllUsesWith( LLVMMetadataRef TempTargetMetadata, LLVMMetadataRef Replacement );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateTempGlobalVariableFwdDecl"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateTempGlobalVariableFwdDecl( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, [MarshalAs( UnmanagedType.LPStr )]string Linkage, size_t LnkLen, LLVMMetadataRef File, uint LineNo, LLVMMetadataRef Ty, [MarshalAs( UnmanagedType.Bool )]bool LocalToUnit, LLVMMetadataRef Decl, global::System.UInt32 AlignInBits );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderInsertDeclareBefore"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMValueRef LLVMDIBuilderInsertDeclareBefore( LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderInsertDeclareAtEnd"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMValueRef LLVMDIBuilderInsertDeclareAtEnd( LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderInsertDbgValueBefore"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMValueRef LLVMDIBuilderInsertDbgValueBefore( LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderInsertDbgValueAtEnd"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMValueRef LLVMDIBuilderInsertDbgValueAtEnd( LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateAutoVariable"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateAutoVariable( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, LLVMMetadataRef File, uint LineNo, LLVMMetadataRef Ty, [MarshalAs( UnmanagedType.Bool )]bool AlwaysPreserve, LLVMDIFlags Flags, global::System.UInt32 AlignInBits );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDIBuilderCreateParameterVariable"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMDIBuilderCreateParameterVariable( LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, [MarshalAs( UnmanagedType.LPStr )]string Name, size_t NameLen, uint ArgNo, LLVMMetadataRef File, uint LineNo, LLVMMetadataRef Ty, [MarshalAs( UnmanagedType.Bool )]bool AlwaysPreserve, LLVMDIFlags Flags );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMGetSubprogram"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMGetSubprogram( LLVMValueRef Func );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMSetSubprogram"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMSetSubprogram( LLVMValueRef Func, LLVMMetadataRef SP );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMDISubprogramGetLine"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern uint LLVMDISubprogramGetLine( LLVMMetadataRef Subprogram );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMInstructionGetDebugLoc"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataRef LLVMInstructionGetDebugLoc( LLVMValueRef Inst );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMInstructionSetDebugLoc"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMInstructionSetDebugLoc( LLVMValueRef Inst, LLVMMetadataRef Loc );

        /// <include file="../../ApiDocs/llvm-c/DebugInfo.xml" path='LibLlvmAPI/Function[@name="LLVMGetMetadataKind"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMetadataKind LLVMGetMetadataKind( LLVMMetadataRef Metadata );

    }
}
