// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0-alpha.3.0.ci-ZZZ.503841922
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Ubiquity.NET.Llvm.Interop
{
    /// <summary>Simple typesafe handle to wrap a raw pointer for interop with "C" API exported from LibLLVM</summary>
    /// <remarks>
    ///    This handle is owned by it's container and therefore isn't disposed by the
    ///    calling App.
    /// <note type="important">
    ///     Since the object this handle refers to is not owned by the App, the object is
    ///     destroyed whenever it's container is destroyed, which will invalidate this handle.
    ///     Use of this handle after the container is destroyed will produce undefined
    ///     behavior, including, and most likely, memory access violations.
    /// </note>
    /// </remarks>
    [GeneratedCode("LlvmBindingsGenerator","10.0.0-alpha.3.0.ci-ZZZ.503841922")]
    public struct LLVMMetadataRef
        : IEquatable<LLVMMetadataRef>
    {
        /// <inheritdoc/>
        public override int GetHashCode( ) => Handle.GetHashCode( );

        /// <inheritdoc/>
        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMMetadataRef r )
             && ( r.Handle == Handle );

        /// <summary>Tests another for reference equality</summary>
        /// <param name="other">Other block to compare</param>
        /// <returns><see langword="true"/> if the other handle refers to the same native object (e.g. reference equality)</returns>
        public bool Equals( LLVMMetadataRef other ) => Handle == other.Handle;

        /// <summary>Fluent null handle validation</summary>
        /// <param name="message">Message to use for an exception if thrown</param>
        /// <param name="memberName">Name if the member calling this function (usually provided by compiler via <see cref="CallerMemberNameAttribute"/></param>
        /// <param name="sourceFilePath">Source file path of the member calling this function (usually provided by compiler via <see cref="CallerFilePathAttribute"/></param>
        /// <param name="sourceLineNumber">Source file path of the member calling this function (usually provided by compiler via <see cref="CallerLineNumberAttribute"/></param>
        /// <returns>This object for fluent style use</returns>
        public LLVMMetadataRef ThrowIfInvalid(
            string message = "",
            [CallerMemberNameAttribute] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0 )
        {
            if( Handle == IntPtr.Zero )
            {
                throw new LlvmException( $"[{memberName}] - {sourceFilePath}@{sourceLineNumber} {message} " );
            }

            return this;
        }

        /// <summary>Tests two handles for reference equality</summary>
        /// <param name="lhs">Left side of comparison</param>
        /// <param name="rhs">Right side of comparison</param>
        /// <returns><see langword="true"/> if both handles refer to the same native object (e.g. reference equality)</returns>
        public static bool operator ==( LLVMMetadataRef lhs, LLVMMetadataRef rhs )
            => EqualityComparer<LLVMMetadataRef>.Default.Equals( lhs, rhs );

        /// <summary>Tests two handles for reference inequality</summary>
        /// <param name="lhs">Left side of comparison</param>
        /// <param name="rhs">Right side of comparison</param>
        /// <returns><see langword="false"/> if both handles refer to the same native object (e.g. reference equality)</returns>
        public static bool operator !=( LLVMMetadataRef lhs, LLVMMetadataRef rhs ) => !( lhs == rhs );

        /// <summary>Gets a zero (<see langword="null"/>) value handle</summary>
        public static LLVMMetadataRef Zero { get; } = new LLVMMetadataRef(IntPtr.Zero);

        /// <summary>Gets the handle as an <see cref="IntPtr"/> suitable for passing to native code</summary>
        /// <returns>The handle as an <see cref="IntPtr"/></returns>
        public IntPtr ToIntPtr() => Handle;

        /// <summary>Gets the handle as an <see cref="IntPtr"/> suitable for passing to native code</summary>
        /// <param name="value">Handle to convert</param>
        /// <returns>The handle as an <see cref="IntPtr"/></returns>
        public static implicit operator IntPtr(LLVMMetadataRef value) => value.ToIntPtr();

        internal LLVMMetadataRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
